/* ═══════════════════════════════════════════════
   Products Database — 12 prodotti e-commerce
   ═══════════════════════════════════════════════ */

const PRODUCTS = [
  {
    id: 1,
    name: 'MacBook Pro 16"',
    category: "elettronica",
    icon: "bi-laptop",
    price: 2499.0,
    originalPrice: 2999.0,
    discount: 17,
    rating: 4.9,
    reviews: 342,
    badge: "Bestseller",
    badgeClass: "bg-primary",
    description:
      "Laptop professionale con chip M3 Pro, display Liquid Retina XDR, 18h di autonomia. Perfetto per sviluppatori e creativi.",
    stock: 15,
  },
  {
    id: 2,
    name: "iPhone 16 Pro Max",
    category: "elettronica",
    icon: "bi-phone",
    price: 1199.0,
    originalPrice: 1499.0,
    discount: 20,
    rating: 4.8,
    reviews: 891,
    badge: "Hot",
    badgeClass: "bg-danger",
    description:
      "Smartphone di ultima generazione con fotocamera da 48MP, chip A18 Pro e display Super Retina XDR da 6.9 pollici.",
    stock: 28,
  },
  {
    id: 3,
    name: "Sony WH-1000XM5",
    category: "elettronica",
    icon: "bi-headphones",
    price: 279.0,
    originalPrice: 399.0,
    discount: 30,
    rating: 4.7,
    reviews: 1205,
    badge: "-30%",
    badgeClass: "bg-danger",
    description:
      "Cuffie wireless premium con cancellazione del rumore leader del settore. 30 ore di autonomia, audio Hi-Res.",
    stock: 42,
  },
  {
    id: 4,
    name: "Giacca Pelle Premium",
    category: "moda",
    icon: "bi-suit-heart",
    price: 189.0,
    originalPrice: 320.0,
    discount: 41,
    rating: 4.6,
    reviews: 234,
    badge: "-41%",
    badgeClass: "bg-warning text-dark",
    description:
      "Giacca in vera pelle italiana lavorata a mano. Design slim fit, fodera in seta. Disponibile in nero e cognac.",
    stock: 8,
  },
  {
    id: 5,
    name: 'Smart TV 4K OLED 65"',
    category: "elettronica",
    icon: "bi-tv",
    price: 1299.0,
    originalPrice: 1899.0,
    discount: 32,
    rating: 4.8,
    reviews: 567,
    badge: "-32%",
    badgeClass: "bg-danger",
    description:
      "TV OLED 4K con processore AI, Dolby Vision & Atmos, gaming a 120Hz. Esperienza cinematografica a casa tua.",
    stock: 12,
  },
  {
    id: 6,
    name: "Sneakers Air Runner",
    category: "sport",
    icon: "bi-dribbble",
    price: 89.9,
    originalPrice: 149.9,
    discount: 40,
    rating: 4.5,
    reviews: 1890,
    badge: "Top Vendite",
    badgeClass: "bg-success",
    description:
      "Sneakers ultraleggere con tecnologia Air Cushion, suola in gomma antiscivolo. Comfort tutto il giorno.",
    stock: 156,
  },
  {
    id: 7,
    name: "Robot Aspirapolvere iX7",
    category: "casa",
    icon: "bi-robot",
    price: 449.0,
    originalPrice: 699.0,
    discount: 36,
    rating: 4.4,
    reviews: 432,
    badge: "-36%",
    badgeClass: "bg-danger",
    description:
      "Robot aspirapolvere con mappatura laser LiDAR, 5000Pa di aspirazione, svuotamento automatico. App smart inclusa.",
    stock: 23,
  },
  {
    id: 8,
    name: "Orologio Chrono Elite",
    category: "moda",
    icon: "bi-smartwatch",
    price: 359.0,
    originalPrice: 499.0,
    discount: 28,
    rating: 4.7,
    reviews: 178,
    badge: "Nuovo",
    badgeClass: "bg-info",
    description:
      "Orologio cronografo in acciaio inossidabile con vetro zaffiro, movimento automatico svizzero. Impermeabile 100m.",
    stock: 19,
  },
  {
    id: 9,
    name: "Set Pentole Chef Pro",
    category: "casa",
    icon: "bi-cup-hot",
    price: 199.0,
    originalPrice: 349.0,
    discount: 43,
    rating: 4.6,
    reviews: 312,
    badge: "-43%",
    badgeClass: "bg-danger",
    description:
      "Set professionale 10 pezzi in acciaio inox 18/10 con fondo a triplo strato. Adatto a tutti i piani cottura.",
    stock: 34,
  },
  {
    id: 10,
    name: "Zaino Trekking 50L",
    category: "sport",
    icon: "bi-backpack2",
    price: 79.9,
    originalPrice: 129.9,
    discount: 38,
    rating: 4.5,
    reviews: 678,
    badge: "-38%",
    badgeClass: "bg-warning text-dark",
    description:
      "Zaino da trekking impermeabile 50L con telaio ergonomico, pannello solare integrato e sistema di idratazione.",
    stock: 67,
  },
  {
    id: 11,
    name: "Tablet Galaxy Ultra",
    category: "elettronica",
    icon: "bi-tablet",
    price: 699.0,
    originalPrice: 899.0,
    discount: 22,
    rating: 4.6,
    reviews: 445,
    badge: "-22%",
    badgeClass: "bg-primary",
    description:
      'Tablet 12.4" AMOLED 120Hz con S Pen inclusa, 256GB, perfetto per produttività e creatività. DeX mode integrato.',
    stock: 31,
  },
  {
    id: 12,
    name: "Lampada Smart RGB",
    category: "casa",
    icon: "bi-lamp",
    price: 49.9,
    originalPrice: 79.9,
    discount: 38,
    rating: 4.3,
    reviews: 923,
    badge: "Popolare",
    badgeClass: "bg-success",
    description:
      "Lampada LED smart con 16 milioni di colori, controllo vocale Alexa/Google, timer e scene personalizzabili.",
    stock: 203,
  },
];

// Valid coupon codes
const COUPONS = {
  VETRINA10: { type: "percent", value: 10, label: "10% di sconto applicato!" },
  SCONTO20: { type: "percent", value: 20, label: "20% di sconto applicato!" },
  RISPARMIA5: { type: "fixed", value: 5, label: "€5 di sconto applicato!" },
  DEMO50: { type: "percent", value: 50, label: "50% di sconto DEMO!" },
};
